org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=aiutd
mod.name=Am I Up To Date?
mod.group=dev.vesper
mod.version=2.0.0

deps.fabric-loader=0.18.4
deps.fabric-loom=1.14-SNAPSHOT
deps.fabric-kotlin=1.13.8+kotlin.2.3.0
deps.moddev=2.0.139
deps.kotlinforforge=6.0.0

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.midnightlib=[VERSIONED]
deps.fancymenu=[VERSIONED]
deps.yacl=[VERSIONED]

publish.modrinth=tgacmJEn
publish.curseforge=
#publish.additionalVersions=