loomx.loom_version="1.17-SNAPSHOT"

mod.id = "aiutd"
mod.name = "Am I Up To Date?"
mod.group = "dev.vesper"
mod.version = "2.5.4"
mod.channel_tag = "-beta.2"
mod.description = "Provides notifications for mod pack updates on the main menu and in chat."
mod.authors = ["VesMaybeVesper"]
#mod.contributors = ["ContributorName", "AnotherContributorName"]
mod.inception_year = "2024"
mod.license.name = "Apache-2.0"
mod.license.url = "https://www.apache.org/licenses/LICENSE-2.0"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/vesmaybevesper/Am-I-Up-To-Date"
mod.homepage_url = "https://modrinth.com/mod/aiutd"
mod.issues_url = "https://github.com/vesmaybevesper/Am-I-Up-To-Date/issues"
#mod.discord_url = ""
mod.environment = "client"
[[mod.pom.developers]]
id = "vesmaybevesper"
name = "VesMaybeVesper"


[fabric]
deps.fabric-loader = "0.19.3"

[fabric."1.20.1"]
deps.minecraft = "1.20.1"
deps.fabric-api = "0.92.11+1.20.1"
deps.modmenu = "7.2.2"
deps.yet_another_config_lib_v3="3.6.6+1.20.1-fabric"
deps.fancymenu="3.9.8-1.20.1-fabric"
deps.rinku="3.0.0-1.20.1"
deps.fastjson4yacl="1.0.5-fabric+1.20.1"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.14+1.21.1"
deps.modmenu = "11.0.4"
deps.yet_another_config_lib_v3="3.8.2+1.21.1-fabric"
deps.fancymenu="3.9.8-1.21.1-fabric"
deps.rinku="3.0.0-1.21.1"
deps.fastjson4yacl="1.0.5-fabric+1.21.1"

[fabric."1.21.11"]
deps.minecraft = "1.21.11"
deps.fabric-api = "0.141.5+1.21.11"
deps.modmenu = "17.0.1-beta.1"
deps.yet_another_config_lib_v3="3.8.2+1.21.11-fabric"
deps.fancymenu="3.9.8-1.21.11-fabric"
deps.rinku="3.0.0-1.21.11"
deps.fastjson4yacl="1.0.5-fabric+1.21.5"

[fabric."26.1"]
deps.minecraft = "26.1"
deps.fabric-api = "0.146.1+26.1.2"
deps.modmenu = "18.0.0"
deps.yet_another_config_lib_v3="3.9.6+26.1-fabric"
deps.fancymenu="3.9.6-26.1.1-fabric"
deps.rinku="3.0.0-26.1.2"
deps.fastjson4yacl="1.0.5-fabric+26.1"
publish.additionalVersions = ["26.1.1", "26.1.2"]

[fabric."26.2"]
deps.minecraft = "26.2"
deps.fabric-api = "0.156.0+26.2"
deps.modmenu = "20.0.1"
deps.yet_another_config_lib_v3="3.9.6+26.2-fabric"
deps.fancymenu="3.9.8-26.2-fabric"
deps.rinku="3.0.0-26.2"
deps.fastjson4yacl="1.0.5-fabric+26.1"
publish.additionalVersions = []

[fabric."26.3"]
deps.minecraft = "26.3-snapshot-7"
deps.fabric-api = "0.156.2+26.3"
deps.modmenu = "21.0.0-alpha.1"
deps.yet_another_config_lib_v3="3.9.6+26.3-fabric"
deps.fancymenu="3.9.8-26.2-fabric"
deps.rinku="3.0.0-26.2"
deps.fastjson4yacl="1.0.5-fabric+26.1"
publish.additionalVersions = []

[forge]

[forge."1.20.1"]
deps.minecraft = "1.20.1"
deps.forge = "47.4.22"
deps.yet_another_config_lib_v3="3.6.6+1.20.1-forge"
deps.fancymenu="3.9.8-1.20.1-forge"
deps.rinku="3.0.0-1.20.1"
deps.fastjson4yacl="1.0.5-forge+1.20.1"

[neoforge]

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.244"
deps.yet_another_config_lib_v3="3.8.2+1.21.1-neoforge"
deps.fancymenu="3.9.8-1.21.1-neoforge"
deps.rinku="3.0.0-1.21.1"
deps.fastjson4yacl="1.0.5-neoforge+1.21.1"

[neoforge."1.21.11"]
deps.minecraft = "1.21.11"
deps.neoforge = "21.11.45"
deps.yet_another_config_lib_v3="3.8.2+1.21.11-neoforge"
deps.fancymenu="3.9.8-1.21.11-neoforge"
deps.rinku="3.0.0-1.21.11"
deps.fastjson4yacl="1.0.5-neoforge+1.21.5"

[neoforge."26.1"]
deps.minecraft = "26.1"
deps.neoforge = "26.1.0.19-beta"
deps.yet_another_config_lib_v3="3.9.6+26.1-neoforge"
deps.fancymenu="3.9.6-26.1.1-neoforge"
deps.rinku="3.0.0-26.1.2"
deps.fastjson4yacl="1.0.5-neoforge+26.1"
publish.additionalVersions = ["26.1.1", "26.1.2"]

[neoforge."26.2"]
deps.minecraft = "26.2"
deps.neoforge = "26.2.0.35-beta"
deps.yet_another_config_lib_v3="3.9.6+26.2-neoforge"
deps.fancymenu="3.9.8-26.2-neoforge"
deps.rinku="3.0.0-26.2"
deps.fastjson4yacl="1.0.5-neoforge+26.1"
publish.additionalVersions = []
