modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "aiutd"
displayName = "Am I Up To Date?"
version = "${version}"
displayURL = ""
logoFile = "assets/icon.png"
authors = "VesMaybeVesper"
description = '''Checks for modpack updates'''

[[mixins]]
config = "aiutd.mixins.json"

[[dependencies.aiutd]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.aiutd]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.7.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.aiutd]]
modId = "minecraft"
type = "required"
